# Generated by Django 3.1 on 2021-06-18 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Warehouse name')),
                ('is_active', models.BooleanField(default=False)),
                ('address1', models.CharField(max_length=255, verbose_name='First address')),
                ('address2', models.CharField(max_length=255, verbose_name='Second address')),
                ('city', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('zip', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Date of change')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Date of change')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
        ),
    ]
